CC=g++
PROGRAM_NAME := gemm_program

all: $(PROGRAM_NAME).cpp
	$(CC) -std=c++11 $(PROGRAM_NAME).cpp -o $(PROGRAM_NAME)

clean:
	rm -f $(PROGRAM_NAME)
	rm -f $(PROGRAM_NAME).bin
	rm -f $(PROGRAM_NAME).txt